apiVersion: apps/v2
kind: Deployment
metadata:
  name: complete-prodcution-e2e-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: complete-prodcution-e2e-deployment
  template:
    metadata:
      labels:
        app: complete-prodcution-e2e-deployment
    spec:
      containers:
      - name: complete-prodcution-e2e-container
        image: ahmedmadara/complete-prodcution-e2e-pipeline:1.0.0-25
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
